# Book settings
title: FunGen-xQTL Manuscript Repository
author: FunGen-AD Consortium
copyright: "2025"  # Current year

# Disable notebook execution to avoid kernel issues
execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file for citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/StatFunGen/xqtl-paper
  branch: main

# Add GitHub buttons to your book
html:
  use_issues_button: true
  use_repository_button: true
